# This workflow will install Python dependencies and run pytest tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master, PR_CI ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        python setup.py install

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        sudo conda env update --file environment.yml --name base

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        C:\Miniconda\condabin\conda.bat env update --file environment.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell

    - name: Test with pytest (Linux)
      if: runner.os == 'Linux'
      run: |
        pip install pytest
        cd tests
        $CONDA/bin/pytest

    - name: Test with pytest (macOS)
      if: runner.os == 'macOS'
      run: |
        sudo conda install pytest
        cd tests
        $CONDA/bin/pytest

    - name: Test with pytest (Windows)
      if: runner.os == 'Windows'
      run: |
        C:\Miniconda\condabin\conda.bat activate base
        C:\Miniconda\condabin\conda.bat install pytest
        cd tests
        C:\Miniconda\Scripts\pytest
